version: '3.8'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: coruss
      POSTGRES_USER: coruss
      POSTGRES_PASSWORD: Ricardo2602
    ports:
      - 5432:5432
    restart: on-failure:3

  pgweb:
    image: sosedoff/pgweb
    depends_on:
      - postgres
    environment:
      PGWEB_DATABASE_URL: postgresql://ricardo2602:AlMCyWmPNsYbMEfdnPia4w@db-coruss-1604.g8x.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full
    ports:
      - 8085:8081
    restart: on-failure:3

  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - redis-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    networks:
      - redis-network
    depends_on:
      - redis

volumes:
  redis:
  redis-config:


networks:
  redis-network:
    driver: bridge
